---

- name: Simple ansible module
  tags: simple
  block:

   - name: Test simple ansible module
     simple_module:
      name: earth
     register: result

   - name: Debug result
     ansible.builtin.debug:
      var: result
