---
name: Ansible Simple Module

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: shallow checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: lint ansible playbooks
        uses: ansible/ansible-lint@main
        env:
          ANSIBLE_LIBRARY: ./library

      - name: run playbook
        uses: dawidd6/action-ansible-playbook@v9
        env:
          ANSIBLE_LIBRARY: ./library
        with:
          playbook: site.yaml
          inventory: inventory.yaml
